apiVersion: v1
data:
   # base64 encode the .dockerconfigjson value before applying to the k8s cluster
  .dockerconfigjson: '{"auths":{"https://registry-1.docker.io":{"username":"<your_username>","password":"<your_password>","email":"<your_email>","auth":"<your_access_token>"}}}'
kind: Secret
metadata:
  name: privatereg
  namespace: argocd
type: kubernetes.io/dockerconfigjson
